### ISSUE TITLE
Questions for the Wiki

### ISSUE THREAD

**Issue by bettinardi** [tlumip/CALM#1]
When describe content in the output version files, we would like the skims / demand matrices defined and a column (description) for which matrices (might just make sense for skims) are used in JEMnR vs the university model.

**Comment by mmmccarthy** [comment]
The skims available to the University model and JEMnR are listed on the Model Outputs page here: https://github.com/tlumip/CALM/wiki/Model-Outputs#skims-used-by-jemnr-and-the-university-model

**Comment by bettinardi** [comment]
Thanks Michael.  This should work, and we will address with new comments if questions still stand
